// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecodeViagens.Models;

#nullable disable

namespace RecodeViagens.Migrations
{
    [DbContext(typeof(GeralDbContext))]
    partial class GeralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecodeViagens.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("RecodeViagens.Models.Destino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("RecodeViagens.Models.Pacote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("Diaria")
                        .HasColumnType("bigint");

                    b.Property<string>("Modal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<long?>("id_destino")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_destino");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("RecodeViagens.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_cargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_cargo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RecodeViagens.Models.Pacote", b =>
                {
                    b.HasOne("RecodeViagens.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("id_destino");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("RecodeViagens.Models.Usuario", b =>
                {
                    b.HasOne("RecodeViagens.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("id_cargo");

                    b.Navigation("Cargo");
                });
#pragma warning restore 612, 618
        }
    }
}
